### ISSUE TITLE
Best practice for programmatically controlling the player?

### ISSUE THREAD

**Issue by paulwehner** [compedit/react-youtube#19]
What would you consider to be the best approach to programmatically control the player? I could see two approaches:

1) Exposing the _internalPlayer to the Parent component, and allowing the parent to make calls against _internalPlayer directly

2) Augmenting react-youtube component, so that Parent components can pass in player commands. _interalPlayer thus remains hidden from the Parent component, and the logic for calling those commands is maintained within react-youtube.

**Comment by compedit** [comment]
I suppose 1 would be the easiest option. We could pass the internal player up via `onReady`, but it feels kinda dirty honestly. thoughs?

**Comment by paulwehner** [comment]
For now I'm going with option 1. I agree its a little dirty, but its the easiest and prevents you from having to rewrite all the API methods. If I run into any issues I'll provide an update.

**Comment by compedit** [comment]
Player is now accessible in every event handler, similar to the official API. See a3c2479ba729aad50db97e7214fea4ff31014a95, 932fc99b8372343438ccbbbccd97c2c475f9e96f

Thanks for the ideas & help!
